jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

 - name: Setup SSH
  shell: bash
  run: |
    set -e

    mkdir -p "$HOME/.ssh"
    chmod 700 "$HOME/.ssh"

    echo "${{ secrets.EC2_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
    chmod 600 "$HOME/.ssh/id_ed25519"

    ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> "$HOME/.ssh/known_hosts"


      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/marketplace
            git pull origin main
            npm install
            npx prisma generate
            npm run build
            pm2 restart all || pm2 start npm --name marketplace -- start
          EOF
