name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          # Use /tmp/.ssh instead of ~/.ssh to avoid permission issues
          mkdir -p /tmp/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/.ssh/id_rsa
          chmod 600 /tmp/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> /tmp/.ssh/known_hosts
          
          # Ensure SSH uses our custom directory
          echo "IdentityFile /tmp/.ssh/id_rsa" >> /tmp/.ssh/config
          chmod 600 /tmp/.ssh/config

      - name: Deploy to EC2
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          # Use the custom SSH directory
          export GIT_SSH_COMMAND="ssh -F /tmp/.ssh/config -o UserKnownHostsFile=/tmp/.ssh/known_hosts"
          
          ssh -F /tmp/.ssh/config \
              -o StrictHostKeyChecking=yes \
              "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" << 'EOF'
            set -e
            cd /var/www/marketplace
            git pull origin main
            npm install
            npx prisma generate
            npm run build
            pm2 restart marketplace || pm2 start npm --name marketplace -- run start
          EOF