name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          # Create SSH directory in workspace instead
          SSH_DIR="$HOME/ssh-setup"
          mkdir -p "$SSH_DIR"
          
          # Save private key
          echo "${{ secrets.EC2_SSH_KEY }}" > "$SSH_DIR/id_rsa"
          chmod 600 "$SSH_DIR/id_rsa"
          
          # Get host key and save to known_hosts
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" > "$SSH_DIR/known_hosts"
          
          # Create SSH config
          echo "Host ec2-deploy" >> "$SSH_DIR/config"
          echo "  HostName ${{ secrets.EC2_HOST }}" >> "$SSH_DIR/config"
          echo "  User ${{ secrets.EC2_USER }}" >> "$SSH_DIR/config"
          echo "  IdentityFile $SSH_DIR/id_rsa" >> "$SSH_DIR/config"
          echo "  UserKnownHostsFile $SSH_DIR/known_hosts" >> "$SSH_DIR/config"
          echo "  StrictHostKeyChecking yes" >> "$SSH_DIR/config"
          chmod 600 "$SSH_DIR/config"

      - name: Debug (optional)
        run: |
          echo "Checking SSH setup:"
          ls -la "$HOME/ssh-setup/" || echo "Directory doesn't exist"
          echo "Home directory: $HOME"
          echo "Whoami: $(whoami)"

      - name: Deploy to EC2
        env:
          SSH_DIR: ${{ github.workspace }}/.ssh-temp
        run: |
          SSH_DIR="$HOME/ssh-setup"
          
          # Test SSH connection first
          ssh -F "$SSH_DIR/config" ec2-deploy "echo 'SSH connection successful!'"
          
          # Deploy commands
          ssh -F "$SSH_DIR/config" ec2-deploy << 'EOF'
            set -e
            cd /var/www/marketplace
            git pull origin main
            npm install
            npx prisma generate
            npm run build
            pm2 restart marketplace || pm2 start npm --name marketplace -- run start
          EOF